main = ".open-next/worker.js"
name = "filatrack"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]
[assets]
directory = ".open-next/assets"
binding = "ASSETS"
[dev]
port = 3000
host = "localhost"
[observability.logs]
enabled = true