/**
 * A result from a database action.
 * If there is an error, `data` will be null.
 * `error` is a user-facing error sent back by the API.
 */
export type DBRes<T> = {
    data?: T;
    error?: string;
};

/**
 * Parameters for creating/updating an object in the database.
 * Omits fields like IDs and timestamps that are generated by the database.
 */
export type DBCreateParams<T> = Omit<T, "id" | "createdAt" | "updatedAt" | "userId">
